name: cpr_detaction
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0" # Updated for compatibility with new packages

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.10.5+9 # Version bumped for consistency
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  google_mlkit_pose_detection: ^0.11.0 # Aligned with other packages
  vector_math: ^2.1.4
  cupertino_icons: ^1.0.8

  # --- Added for YOLO Object Detection ---
  flutter_vision: ^1.1.4
  image: ^4.1.7
  # --- End of Added Dependencies ---

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0 # Using a more standard version

# The section below has been corrected.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # This change ensures all files within the models directory are included.
  assets:
    - assets/models/
